FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit

COPY src ./src

EXPOSE 8501

CMD ["streamlit", "run", "src/frontend/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
